module: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-mongo-common
package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-mongo-common/changestream/checkpoint/mdb/checkpointcollection
entities:
- file-name: ./checkpoint.yml
  document: true
  package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-mongo-common/changestream/checkpoint/mdb/checkpointcollection
