module: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-mongo-common
package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-mongo-common/jobs/store/beans
entities:
- file-name: ./job.yml
  document: true
  package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-mongo-common/jobs/store/job
- file-name: ./task.yml
  document: true
  package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-mongo-common/jobs/store/task
- file-name: ./partition.yml
- file-name: ./task-ref.yml
- file-name: ./dd-trigger-chk.yml
  document: true
  package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-mongo-common/jobs/store/ddtcheckpoint
- file-name: ./task-log.yml
  document: true
  package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-mongo-common/jobs/store/tasklog
- file-name: ./task-log-entry.yml
  package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-mongo-common/jobs/store/tasklog